{{- define "cap-app-proxy.environment-variables.init-container-defaults" -}}
CF_HOST:
  valueFrom:
    configMapKeyRef:
      name: codefresh-cm
      key: base-url
CLUSTER:
  valueFrom:
    configMapKeyRef:
      name: codefresh-cm
      key: cluster
INGRESS_CLASS_NAME: 
  valueFrom:
    configMapKeyRef:
      name: codefresh-cm
      key: ingressClassName
INGRESS_CONTROLLER: 
  valueFrom:
    configMapKeyRef:
      name: codefresh-cm
      key: ingressController
INGRESS_HOST: 
  valueFrom:
    configMapKeyRef:
      name: codefresh-cm
      key: ingressHost
NAMESPACE: 
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
RUNTIME_NAME: 
  valueFrom:
    configMapKeyRef:
      name: cap-app-proxy-cm
      key: runtimeName
RUNTIME_TOKEN: 
  valueFrom:
    secretKeyRef:
      name: codefresh-token
      key: token
      optional: true
RUNTIME_VERSION:
  valueFrom:
    configMapKeyRef:
      name: codefresh-cm
      key: version
{{- end -}}

{{/*
Read defaults from the template above and merge with the values provided in values file
*/}}
{{- define "cap-app-proxy.environment-variables.init-container" -}}
{{- $defaults := (include "cap-app-proxy.environment-variables.init-container-defaults" . | fromYaml ) -}}
{{- $overrides := .Values.initContainer.env -}}
{{- $mergedValues := merge $overrides $defaults -}}
{{- include "codefresh-gitops-runtime.components.common_helpers.container-templates.env-vars" $mergedValues -}}
{{- end -}}
