{{- define "event-reporters.workflow-reporter.sensor"}}
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: workflow-reporter
  labels:
    {{- include "event-reporters.workflow-reporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.workflow.sensor.replicas }}
  dependencies:
    - eventName: workflows
      eventSourceName: workflow-reporter
      name: workflows
  eventBusName: {{ .Values.global.runtime.eventBusName }}
  template:
    serviceAccountName: {{ include "event-reporters.workflow-reporter.serviceAccountName" .}}
    container:
      name: ""
      resources:
      {{- with .Values.workflow.sensor.resources  }}
        {{- . | toYaml | nindent 8 }}
      {{- end }}
  triggers:
    - retryStrategy:
        duration: 0
        steps: 3
      template:
        conditions: workflows
        http:
          headers:
            Content-Type: application/json
          method: POST
          payload:
            - dest: data.object
              src:
                dataKey: body
                dependencyName: workflows
          secureHeaders:
            - name: Authorization
              valueFrom:
                secretKeyRef:
                  key: token
                  name: codefresh-token
          url: {{ printf "%s%s" .Values.global.codefresh.url .Values.global.codefresh.apiEventsPath | quote }}
        name: workflows
{{- end }}