{{- if .Values.global.runtime.argoCDApplication.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.runtime.argoCDApplication.name }}
  labels:
    {{- include "codefresh-gitops-runtime.labels" . | nindent 4 }}
spec:
  project: default
  source:
    chart: gitops-runtime-sandbox
    repoURL: {{ .Values.global.runtime.argoCDApplication.chartRepo }}
    targetRevision: {{ .Values.global.runtime.argoCDApplication.chartVersion | default .Chart.Version }}
    helm:
      releaseName: {{ .Release.Name }}
      values: |
{{ .Values | toYaml | toString | indent 8 | default "" }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ .Release.Namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}